<a href="https://colab.research.google.com/github/chaitalijadhao206-star/Numpy-Session-13/blob/main/_zeros_and_ones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Create 1D array of zeros
arr1 = np.zeros(8)

# Print 1D array
print("1D Array of Zeros:")
print(arr1)

# Create 2D array of ones
arr2 = np.ones((4, 4))

# Print 1D array
print("\n2D Array of ones:")
print(arr2)

# Create 3x3 matrix of zeros
arr3 = np.zeros((3, 3))

# Print 3x3 matrix
print("\n3x3 Matrix of Zeros:")
print(arr3)





1D Array of Zeros:
[0. 0. 0. 0. 0. 0. 0. 0.]

2D Array of ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

3x3 Matrix of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
