<a href="https://colab.research.google.com/github/chaitalijadhao206-star/Numpy-Session-13/blob/main/Q_10_Simple_Calculation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
# Get number of random numbers
n = int(input("Enter number of elements: "))

# Generate random numbers
arr = np.random.randint(10, 101, n)

# Print array
print("\nArray:")
print(arr)

# Print statistics
print("\nMean:", np.mean(arr))
print("\nMedian:", np.median(arr))
print("\nStandard Deviation:", np.std(arr))
print("\nMinimum:", np.min(arr))
print("\nMaximum:", np.max(arr))

# Reshape into 2D array if possible
if n % 2 == 0:
    arr2 = arr.reshape(2, n // 2)

    print("2D Array:")
    print(arr2)

    print("Row-wise Sum:")
    print(np.sum(arr2, axis=1))
else:
    print("Cannot reshape into 2D array")

Enter number of elements: 10

Array:
[53 99 86 22 38 90 54 58 90 61]

Mean: 65.1

Median: 59.5

Standard Deviation: 23.9893726470702

Minimum: 22

Maximum: 99
2D Array:
[[53 99 86 22 38]
 [90 54 58 90 61]]
Row-wise Sum:
[298 353]
