<a href="https://colab.research.google.com/github/chaitalijadhao206-star/Numpy-Session-13/blob/main/Q_5_Random_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
# Create 1D array of 10 random numbers
arr=np.random.rand(10)

# Print first array
print("Random Numbers (0 to 1):")
print(arr)

# Create 3x3 matrix of random numbers
arr=np.random.randn(3, 3)

# Print second array
print("\n3x3 Random Matrix:")
print(arr)

# Create 4x5 matrix of random integers
arr=np.random.randint(10, 51, (4, 5))

# Print third array
print("\n4x5 Random Integer Matrix:")
print(arr)

Random Numbers (0 to 1):
[0.08926841 0.4935565  0.6029018  0.08912004 0.21247072 0.77403909
 0.12608569 0.79420384 0.11866436 0.99074995]

3x3 Random Matrix:
[[ 0.89225019  0.75915048 -1.24636961]
 [ 0.01788547  0.07014912  0.30356066]
 [-0.67088469 -1.86837334 -0.05148994]]

4x5 Random Integer Matrix:
[[40 19 43 18 24]
 [37 43 26 50 48]
 [24 34 27 40 12]
 [16 37 45 41 11]]
