<a href="https://colab.research.google.com/github/chaitalijadhao206-star/Numpy-Session-13/blob/main/Q_7_Matrices_and_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [4]:
# Create first matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("Matrix A:")
print(A)

# Create second matrix
B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])
print("\nMatrix B:")
print(B)

# Matrix addition
add = A + B
print("\nMatrix Addition:")
print(add)

# Matrix multiplication
mul = A @ B
print("\nMatrix Multiplication:")
print(mul)

# Element-wise multiplication
ele_mul = A * B
print("\nElement-wise Multiplication:")
print(ele_mul)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
