<a href="https://colab.research.google.com/github/chaitalijadhao206-star/Numpy-Session-13/blob/main/Q_8_Properties_of_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
# Create 4x4 random matrix
arr = np.random.randint(1, 101, (4, 4))

print("4x4 Matrix:")
print(arr)

# Print shape
print("\nShape:", arr.shape)

# Print dimension
print("\nDimension:", arr.ndim)

# Print total elements
print("\nSize:", arr.size)

# Print data type
print("\nData Type:", arr.dtype)

# Print minimum value
print("\nMinimum Value:", arr.min())

# Print maximum value
print("\nMaximum Value:", arr.max())

4x4 Matrix:
[[73  2 69  3]
 [63 77 82 13]
 [78 39 97 90]
 [80 62  6 57]]

Shape: (4, 4)

Dimension: 2

Size: 16

Data Type: int64

Minimum Value: 2

Maximum Value: 97
