<a href="https://colab.research.google.com/github/chaitalijadhao206-star/Numpy-Session-13/blob/main/Q_9_Combined.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Create 1D array of 20 random integers
arr = np.random.randint(1, 51, 20)

# Reshape into 4x5 matrix
mat = arr.reshape(4, 5)

# Print matrix
print("4x5 Matrix:")
print(mat)

print()

# Print sum
print("Sum:", np.sum(mat))

# Print mean
print("Mean:", np.mean(mat))

# Print standard deviation
print("Standard Deviation:", np.std(mat))

print()

# Print maximum value of each row
print("Maximum Value in Each Row:")
print(np.max(mat, axis=1))

4x5 Matrix:
[[41 43 32  4 45]
 [ 8 23 21  2 14]
 [16 16 27 48 15]
 [12 18 18 30 24]]

Sum: 457
Mean: 22.85
Standard Deviation: 13.085392619252966

Maximum Value in Each Row:
[45 23 48 30]
